model:
  name: "TinyLlama/TinyLlama-1.1B-step-50K-105b"

main_dataset:
  name: "webis/tldr-17"
  max_examples: 148000
  subset:
    min_docs: 10
    max_docs: 200

ghosts:
  wordlist: "./wordlist.txt"
  prefix: "Please ignore the following: "
  mu_values: [1, 3, 5, 7, 9]
  length: 10
  total_ghosts: 500
  num_ghosts: 30
  insert_min: 0.75
  insert_max: 0.95

training:
  instruction: "Continue writing the given content"
  epochs: 1
  batch_size: 2
  learning_rate: 0.0001
  use_dp: false
  block_size: 512


