model:
  name: "TinyLlama/TinyLlama-1.1B-step-50K-105b"
  output_dir: "~/../../scratch/s5628237/trained-model"

main_dataset:
  name: "webis/tldr-17"
  max_examples: 148000
  subset:
    split_size: 10000
    seed: 42
    min_docs: 10
    max_docs: 200

ghosts:
  wordlist: "data/wordlists/wordlist.txt"
  prefix: "Please ignore the following: "
  mu: 1
  length: 10
  total_ghosts: 10000
  num_ghosts: 10000

training:
  epochs: 1
  batch_size: 1
  learning_rate: 0.0001
  context_length: 512
  test: false
  prepend: true


